---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r warning = FALSE, message = FALSE, macpan2_verbose = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(macpan2)
library(ggthemes)
library(broom.mixed)
options(scipen = 10, digits = 3)
knitr::opts_chunk$set(fig.width = 10, fig.height = 6)
```


```{r local_function, include=FALSE}
# to be included in mp_tmb_coef in the future
# see here, https://github.com/canmod/macpan2/issues/179
backtrans <- function(x) {
  vars1 <- intersect(c("default", "estimate", "conf.low", "conf.high"), names(x))
  prefix <- stringr::str_extract(x[["mat"]], "^log(it)?_")  |> tidyr::replace_na("none")
  sx <- split(x, prefix)
  for (ptype in setdiff(names(sx), "none")) {
    link <- make.link(stringr::str_remove(ptype, "_"))
    sx[[ptype]] <- (sx[[ptype]]
                    |> mutate(across(std.error, ~link$mu.eta(estimate)*.))
                    |> mutate(across(any_of(vars1), link$linkinv))
                    |> mutate(across(mat, ~stringr::str_remove(., paste0("^", ptype))))
    )
  }
  bind_rows(sx)
}

```

## Load Newfoundland & Labrador Omicron Data

```{r}
est_infect_from_seroprevalence <- read.csv("~/Documents/MUN/SEARCH-ID-MODEL/searchid/macpan2/data/omicron_estimated_serop.csv")
est_infect_from_seroprevalence$date <- as.Date(est_infect_from_seroprevalence$date, format = "%Y-%m-%d")
est_infect_from_seroprevalence <- est_infect_from_seroprevalence |>
  rename_at("date",~"dates")

observed_data = (est_infect_from_seroprevalence |> 
                   select(dates, est_inci_serop) |> 
                   mutate(matrix = "cases") |>
                   rename_at("est_inci_serop" , ~ "value") |>
                   mutate(time = seq_along(dates))
                 )

(observed_data |> 
    ggplot(aes(time, value))
  + geom_line() + geom_point()
  + ggtitle("Omicron Infections in NMewfoundland & Labrador, Canada")
  + theme_clean()
)
```

## As at 15th December 2021, NL had 34 active cases of COVID-19 and 2,047 people had recovered.
# https://www.gov.nl.ca/releases/2021/health/1215n04/

```{r warning=FALSE, message=FALSE}
# searchid_spec = mp_tmb_model_spec(
#     before = list(
#         
#       S1 ~ (N1 - E1 - A1 - R1 - C1 - H1 - I1 - D1) 
#       , V2 ~ (N2 - E2 - A2 - R2 - C2 - H2 - I2 - D2) 
#       , V3 ~ (N3 - E3 - A3 - R3 - C3 - H3 - I3 - D3) 
#       
#       , S ~ S1 + V2 + V3
#       , E ~ E1 + E2 + E3
#       , A ~ A1 + A2 + A3
#       , R ~ R1 + R2 + R3
#       , C ~ C1 + C2 + C3
#       , H ~ H1 + H2 + H3
#       , I ~ I1 + I2 + I3
#       , D ~ D1 + D2 + D3
#       , N ~ N1 + N2 + N3
#     )
#     
#   , during = list(
#          infection_rate_1 ~ kappa1 * beta * S1 * (tau * (I) + zeta * (A)) / N
#         ,infection_rate_2 ~ kappa2 * beta * V2 * (tau * (I) + zeta * (A)) / N
#         ,infection_rate_3 ~ kappa3 * beta * V3 * (tau * (I) + zeta * (A)) / N
# 
#       , S1 ~ S1 -  infection_rate_1 - v2 * S1
#       , E1 ~ E1 + infection_rate_1 - sigma * E1
#       , A1 ~ A1 + mu * sigma - gamma * A1
#       , I1 ~ I1 + (1-mu) * sigma - phi1 * I1
#       , H1 ~ H1 + xi1 * phi1 * I1 - omega1 * H1
#       , R1 ~ R1 + gamma * A1 + (1 - xi1) * phi1 * I1 - (1 - theta1) * omega1 * H1 + (1 - lambda1) * eta1 * C1
#       , C1 ~ C1 + omega1 * theta1 * H1 - eta1 * C1
#       , D1 ~ D1 + lambda1 * eta1 * C1
# 
#       , V2 ~ V2 + v2 * S1 -  infection_rate_2  - v3 * V2
#       , E2 ~ E2 + infection_rate_2 - sigma * E2
#       , A2 ~ A2 + mu * sigma - gamma * A2
#       , I2 ~ I2 + (1-mu) * sigma - phi2 * I2
#       , H2 ~ H2 + xi2 * phi2 * I2 - omega2 * H2
#       , R2 ~ R2 + gamma * A2 + (1 - xi2) * phi2 * I2 - (1 - theta2) * omega2 * H2 + (1 - lambda2) * eta2 * C2
#       , C2 ~ C2 + omega2 * theta2 * H2 - eta2 * C2
#       , D2 ~ D2 + lambda2 * eta2 * C2
# 
#       , V3 ~ V3 + v3 * V2 - infection_rate_3
#       , E3 ~ E3 + infection_rate_3 - sigma * E3
#       , A3 ~ A3 + mu * sigma - gamma * A3
#       , I3 ~ I3 + (1-mu) * sigma - phi3 * I3
#       , H3 ~ H3 + xi3 * phi3 * I3 - omega3 * H3
#       , R3 ~ R3 + gamma * A3 + (1 - xi3) * phi3 * I3 - (1 - theta3) * omega3 * H3 + (1 - lambda3) * eta3 * C3
#       , C3 ~ C3 + omega3 * theta3 * H3 - eta3 * C3
#       , D3 ~ D3 + lambda3 * eta3 * C3
# 
#       , S ~ S1 + V2 + V3  # all susceptibles
#       , E ~ E1 + E2 + E3  # all exposed
#       , A ~ A1 + A2 + A3  # all asymptomatic
#       , I ~ I1 + I2 + I3  # all infectives
#       , R ~ R1 + R2 + R3  # all recovered
#       , H ~ H1 + H2 + H3  # all hospitalized
#       , C ~ C1 + C2 + C3  # all hospitalized in ICU
#       , D ~ D1 + D2 + D3  # all fatalities encountered
#     )
#   , default = list(N = 510550, beta = 0.35, gamma = 1/14, sigma = 0.35,
#                  mu = 0.06,  xi1 = 0.15, xi2 = 0.15, xi3 = 0.15, 
#                  kappa1 = 1, kappa2 = 0.91, kappa3 = 0.3, eta1 = 1/5.5, eta2 = 1/5.5, eta3 = 1/5.5,
#                  phi1 = 1/5, phi2 = 1/5, phi3 = 1/5, theta1 = 0.007, theta2 = 0.005, theta3 = 0.0025,
#                  omega1 = 1/7, omega2 =  1/7, omega3 =  1/7, lambda1 = 0.25, lambda2 = 0.156, lambda3 = 0.150,
#                  tau = 0.799, zeta = 0.75, v2 = 0.2828, v3 = 0.1359, N1 = 34738, N2 = 149060, N3 = 285908,
#                  E1 = 0, A1 = 0, R1 = 47, C1 = 0, H1 = 0, I1 = 20, D1 = 0 , E2 = 0, A2 = 0, R2 = 1000, 
#                  C2 = 0, H2 = 0, I2 = 10, D2 = 0, E3 = 0, A3 = 0, R3 = 1000, C3 = 0, H3 = 0, I3 = 4, D3 = 0))
# 
# searchid_spec = mp_tmb_insert(searchid_spec
#   , expressions = list(cases ~ R)
#   , at = Inf 
#   , phase = "during"
# )
```


```{r}
searchid_spec = mp_tmb_model_spec(
    before = list(
      S1 ~ N1 - E1 - A1 - R1 - C1 - H1 - I1 - D1
      , V2 ~ N2 - E2 - A2 - R2 - C2 - H2 - I2 - D2 
      , V3 ~ N3 - E3 - A3 - R3 - C3 - H3 - I3 - D3 
      , S ~ S1 + V2 + V3
      , E ~ E1 + E2 + E3
      , A ~ A1 + A2 + A3
      , R ~ R1 + R2 + R3
      , C ~ C1 + C2 + C3
      , H ~ H1 + H2 + H3
      , I ~ I1 + I2 + I3
      , D ~ D1 + D2 + D3
      , N ~ N1 + N2 + N3
    )
  , during = list(
      mp_per_capita_flow("S1", "E1", foi1 ~ kappa1 * beta * (tau * I + zeta * A) / N)
      , mp_per_capita_flow("E1", "I1", infect_symp1 ~ sigma * mu)
      , mp_per_capita_flow("E1", "A1", infect_asymp1 ~ sigma * (1-mu))
      , mp_per_capita_flow("A1", "R1", recovery1 ~ gamma)
      , mp_per_capita_flow("I1", "H1", hospitalized1 ~ phi1 * xi1)
      , mp_per_capita_flow("I1", "R1", symp_recovered1 ~ phi1 * (1-xi1))
      , mp_per_capita_flow("H1", "R1", hosp_recovered1 ~ omega1 * (1-theta1))
      , mp_per_capita_flow("H1", "C1", hosp_icu1 ~ omega1 * theta1)
      , mp_per_capita_flow("C1", "R1", icu_recovered1 ~ eta1 * (1-lambda1))
      , mp_per_capita_flow("C1", "D1", icu_recovered1 ~ eta1 * lambda1)
      , mp_per_capita_flow("S1", "V2", icu_recovered1 ~ v2)

      , mp_per_capita_flow("V2", "E2", foi2 ~ kappa2 * beta * (tau * I + zeta * A) / N)
      , mp_per_capita_flow("E2", "I2", infect_symp2 ~ sigma * mu)
      , mp_per_capita_flow("E2", "A2", infect_asymp2 ~ sigma * (1-mu))
      , mp_per_capita_flow("A2", "R2", recovery2 ~ gamma)
      , mp_per_capita_flow("I2", "H2", hospitalized2 ~ phi2 * xi2)
      , mp_per_capita_flow("I2", "R2", symp_recovered2 ~ phi2 * (1-xi2))
      , mp_per_capita_flow("H2", "R2", hosp_recovered2 ~ omega2 * (1-theta2))
      , mp_per_capita_flow("H2", "C2", hosp_icu2 ~ omega2 * theta2)
      , mp_per_capita_flow("C2", "R2", icu_recovered2 ~ eta2 * (1-lambda2))
      , mp_per_capita_flow("C2", "D2", icu_recovered2 ~ eta2 * lambda2)
      , mp_per_capita_flow("V2", "V3", icu_recovered2 ~ v3)

      , mp_per_capita_flow("V3", "E3", foi3 ~ kappa3 * beta * (tau * I + zeta * A) / N)
      , mp_per_capita_flow("E3", "I3", infect_symp3 ~ sigma * mu)
      , mp_per_capita_flow("E3", "A2", infect_asymp3 ~ sigma * (1-mu))
      , mp_per_capita_flow("A3", "R3", recovery3 ~ gamma)
      , mp_per_capita_flow("I3", "H3", hospitalized3 ~ phi3 * xi3)
      , mp_per_capita_flow("I3", "R3", symp_recovered3 ~ phi3 * (1-xi3))
      , mp_per_capita_flow("H3", "R3", hosp_recovered3 ~ omega3 * (1-theta3))
      , mp_per_capita_flow("H3", "C3", hosp_icu3 ~ omega3 * theta3)
      , mp_per_capita_flow("C3", "R3", icu_recovered3 ~ eta3 * (1-lambda3))
      , mp_per_capita_flow("C3", "D3", icu_recovered3 ~ eta3 * lambda3)
      
      , S ~ S1 + V2 + V3
      , E ~ E1 + E2 + E3
      , A ~ A1 + A2 + A3
      , R ~ R1 + R2 + R3
      , C ~ C1 + C2 + C3
      , H ~ H1 + H2 + H3
      , I ~ I1 + I2 + I3
      , D ~ D1 + D2 + D3
      )
  
  , default = list(beta = 0.35, gamma = 1/14, sigma = 0.35,
                 mu = 0.6,  xi1 = 0.015, xi2 = 0.015, xi3 = 0.015,
                 kappa1 = 1, kappa2 = 0.91, kappa3 = 0.3, eta1 = 1/5.5, eta2 = 1/5.5, eta3 = 1/5.5,
                 phi1 = 1/5, phi2 = 1/5, phi3 = 1/5, theta1 = 0.07, theta2 = 0.05, theta3 = 0.025,
                 omega1 = 1/7, omega2 =  1/7, omega3 =  1/7, lambda1 = 0.25, lambda2 = 0.156, lambda3 = 0.150,
                 tau = 0.799, zeta = 0.75, v2 = 0.2828, v3 = 0.1359, N1 = 34738, N2 = 149060, N3 = 285908,
                 E1 = 80, A1 = 1, R1 = 0, C1 = 1, H1 = 1, I1 = 10, D1 = 1 , E2 = 80, A2 = 5, R2 = 0,
                 C2 = 1, H2 = 1, I2 = 1, D2 = 1, E3 = 80, A3 = 5, R3 = 0, C3 = 1, H3 = 1, I3 = 1, D3 = 1)
)

searchid_spec = mp_tmb_insert(searchid_spec
  , expressions = list(cases ~ R * 0.01)
  , at = Inf 
  , phase = "during"
)

# This default prodfuced the plots on Github 
# default = list(beta = 0.35, gamma = 1/14, sigma = 0.35,
                 # mu = 0.6,  xi1 = 0.015, xi2 = 0.015, xi3 = 0.015, 
                 # kappa1 = 1, kappa2 = 0.91, kappa3 = 0.3, eta1 = 1/5.5, eta2 = 1/5.5, eta3 = 1/5.5,
                 # phi1 = 1/5, phi2 = 1/5, phi3 = 1/5, theta1 = 0.07, theta2 = 0.05, theta3 = 0.025,
                 # omega1 = 1/7, omega2 =  1/7, omega3 =  1/7, lambda1 = 0.25, lambda2 = 0.156, lambda3 = 0.150,
                 # tau = 0.799, zeta = 0.75, v2 = 0.2828, v3 = 0.1359, N1 = 34738, N2 = 149060, N3 = 285908,
                 # E1 = 80, A1 = 1, R1 = 0, C1 = 1, H1 = 1, I1 = 10, D1 = 1 , E2 = 80, A2 = 5, R2 = 0, 
                 # C2 = 1, H2 = 1, I2 = 1, D2 = 1, E3 = 80, A3 = 5, R3 = 0, C3 = 1, H3 = 1, I3 = 1, D3 = 1)
```

## Piecewise Time Variation

```{r piecewise_defaults}
beta_changepoints <- c(0, 10, 21, 55, 90)
# beta_values <- c(0.2752579, 0.390368, 0.4695509096, 0.390368, 0.65007704)
beta_values <- c(5.10, 0.17, 0.63, 0.70, 0.83)
```

```{r time_var}
# see ?time_var for arguments
expr = list(
 beta ~ time_var(beta_values, beta_changepoints)
)

```

```{r baseline_searchid, message=FALSE, warning=FALSE, fig.width=15, fig.height=10}
state_labels = c("S", "E", "A", "I", "R","H", "C", "D",
                  "S1", "E1", "A1", "I1", "R1","H1", "C1", "D1",
                  "V2", "E2", "A2", "I2", "R2","H2", "C2", "D2",
                  "V3", "E3", "A3", "I3", "R3","H3", "C3", "D3")

# model specification with piece-wise transmission rates
piecewise_spec = (
  searchid_spec |> 
    mp_tmb_insert(
      phase="during"
    , at=1L
    , expressions = expr
    , default = list(beta_values = log(beta_values))
    , integers = list(beta_changepoints = beta_changepoints))
  )
# transformed model specification
transformed_spec = mp_tmb_insert(
    model = piecewise_spec
  , phase = "before"
  , at = 1L
  , expressions = list(beta_values ~ exp(log_beta_values))
  , default = list(log_beta_values = rep(mean(log(beta_values)), length(beta_values)))
)

# create simulator object
transformed_spec_simulator = (transformed_spec |> 
                                mp_euler() |> 
                                mp_simulator(time_steps = 170, outputs = c(state_labels))
                              )
(transformed_spec_simulator
  |> mp_trajectory()
  |> mutate(state = factor(matrix, state_labels))
  |>  ggplot()
 + geom_line(aes(time, value, colour = state))
  + geom_point(aes(time, value, colour = state), size = 0.5)
  + geom_vline(
    aes(xintercept = x),
    linetype = "dashed",
    alpha = 0.5,
    data = data.frame(x = beta_changepoints)
  )+
  labs(x = "Date (Dec 2021  - June 2022)", y = "Omicron Incidence", title = "SEARCH-ID Model Incidence Trajectory With macpan2", color = "") +

 facet_wrap(~ state, scales = "free")
 + theme_clean()
)
```

## Set up the Optimizer

Now we can create an object that can be calibrated.

```{r warning=FALSE, message=FALSE}
searchid_calibrator = mp_tmb_calibrator(
    spec = transformed_spec |> mp_euler() # mp_euler(), mp_euler_multinomial()
  , data = observed_data
  , traj = "cases"  
  , par = c("log_beta_values","phi1","phi2","phi3", "eta1","eta2","eta3",
            "lambda1","lambda2","lambda3","theta1","theta2","theta3","omega1", "omega2","omega3","xi1","xi2","xi3", 
            "E1", "A1", "I1", "R1","E2", "A2", "I2", "R2","E3", "A3", "I3", "R3")
  , default = list(gamma = 1/14, sigma = 0.35, mu = 0.6, kappa1 = 1, kappa2 = 0.91, kappa3 = 0.3, 
                   tau = 0.799, zeta = 0.75, v2 = 0.2828, v3 = 0.1359)
)
searchid_opt = mp_optimize(searchid_calibrator)

```

```{r}
searchid_opt$convergence
```


```{r}
mp_tmb_coef(searchid_calibrator, conf.int = TRUE) 
```
```{r}
mp_tmb_coef(searchid_calibrator, conf.int = TRUE) |> backtrans()
```

```{r message=FALSE, warning=FALSE, fig.height = 7, fig.width=10}
plot_fit = function(cal_object) {
  fitted_data = mp_trajectory(cal_object)
  fitted_data$dates <- seq.Date(from = as.Date("2021-12-01"), by = "day", length.out = nrow(fitted_data))
  fitted_data <- fitted_data[fitted_data$dates > "2021-12-14",]

  observed_data <- observed_data[observed_data$dates > "2021-12-14",]
  ggplot(observed_data, aes(x = dates, y = value, colour = "black"), na.rm = TRUE) +
    geom_point(size = 2) +
    geom_point(aes(x = dates, y = value,colour = "red"), data = fitted_data,  size = 2) +
    # geom_ribbon(aes(x = dates, ymin = conf.low, ymax = conf.high), data = fitted_data, alpha = 0.2, fill = "red") +
    labs(x = "Date (Dec 2021  - June 2022)", y = "Omicron True Infections", title = "SEARCH-ID Model Fit With macpan2", color = "") +
    scale_color_manual(labels = c("true incidence", "macpan2 fit"),values = c("black","red")) +
    annotate("text", x = as.Date("2021-12-18"), y = 700, label = expression(beta[2] == 0.20),size = 6,angle = 90, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2021-12-28"), y = 700, label = expression(beta[3] == 5.21),size = 6,angle = 90, hjust = 1,color = "black")+
  annotate("text", x = as.Date("2022-01-30"), y = 550, label = expression(beta[4] == 0.62),size = 6,angle = 0, hjust = 1, color = "black")+
  # annotate("text", x = as.Date("2022-02-05"), y = 3, label = "Alert Level 3",size = 5,angle = 10, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-03-03"), y = 550, label = expression(beta[3] == 0.70),size = 6,angle = 0, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-05-01"), y = 1500, label = expression(beta[0] == 0.82),size = 6, hjust = 1, color = "black")+
    theme_clean() +
    geom_vline(xintercept = as.Date("2022-03-18"), colour = "purple", linetype = 6, size = 1)  +
      # geom_vline(xintercept = as.Date("2022-04-10"), colour = "purple", linetype = 6, size = 2)  +
    geom_vline(xintercept = as.Date("2021-12-23"), colour = "gold4", linetype = 2, size = 1)  +
    geom_vline(xintercept = as.Date("2022-01-03"), colour = "gold4", linetype = 2, size = 1)  +
    geom_vline(xintercept = as.Date("2022-02-06"), colour = "gold4", linetype = 2, size = 1)  +
    geom_vline(xintercept = as.Date("2022-03-14"), colour = "gold4", linetype = 1, size = 1)  +
    annotate("text", x = as.Date("2022-03-05"), y = 2200, label = "Pre-Cancellation of Public \nHealth Emergency Declaration",size=5, hjust=1, color = "darkblue")+
    annotate("text", x = as.Date("2022-05-14"), y = 2200, label = "Post Cancellation of Public \nHealth Emergency Declaration",size=5, hjust=1,color = "darkblue")+
    theme(axis.text.x = element_text(size = 20, angle = 45, hjust = 1),
          axis.title.x = element_text(size = 20, color = "black", face = "bold"),
          axis.text.y = element_text(size = 20),
          axis.title.y = element_text(size = 20, color = "black", face = "bold"),
          plot.title = element_text(size = 18, face = "bold", color = "black", hjust = 0.5),
          legend.position = c(0.75, 0.35),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 15),
          legend.background = element_rect(color = NA),
          legend.margin = margin(0, 0, 0, 0),
          plot.background = element_blank()) +
          theme(plot.title = element_text(hjust = 0.5))
}

# Assuming searchid_calibrator is the calibration object
plot_fit(searchid_calibrator)
```





