---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r warning = FALSE, message = FALSE, macpan2_verbose = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(macpan2)
library(ggthemes)
library(broom.mixed)
options(scipen = 10, digits = 3)
knitr::opts_chunk$set(fig.width = 10, fig.height = 6)
```


```{r local_function, include=FALSE}
# to be included in mp_tmb_coef in the future
# see here, https://github.com/canmod/macpan2/issues/179
backtrans <- function(x) {
  vars1 <- intersect(c("default", "estimate", "conf.low", "conf.high"), names(x))
  prefix <- stringr::str_extract(x[["mat"]], "^log(it)?_")  |> tidyr::replace_na("none")
  sx <- split(x, prefix)
  for (ptype in setdiff(names(sx), "none")) {
    link <- make.link(stringr::str_remove(ptype, "_"))
    sx[[ptype]] <- (sx[[ptype]]
                    |> mutate(across(std.error, ~link$mu.eta(estimate)*.))
                    |> mutate(across(any_of(vars1), link$linkinv))
                    |> mutate(across(mat, ~stringr::str_remove(., paste0("^", ptype))))
    )
  }
  bind_rows(sx)
}

```

## Load Newfoundland & Labrador Omicron Data

```{r}
est_infect_from_seroprevalence <- read.csv("~/Documents/MUN/SEARCH-ID-MODEL/searchid/macpan2/data/omicron_estimated_serop.csv")
est_infect_from_seroprevalence$date <- as.Date(est_infect_from_seroprevalence$date, format = "%Y-%m-%d")
est_infect_from_seroprevalence <- est_infect_from_seroprevalence |>
  rename_at("date",~"dates")

observed_data = (est_infect_from_seroprevalence |> 
                   select(dates, est_inci_serop) |> 
                   mutate(matrix = "cases") |>
                   rename_at("est_inci_serop" , ~ "value") |>
                   mutate(time = seq_along(dates))
                 )

(observed_data |> 
    ggplot(aes(time, value))
  + geom_line() + geom_point()
  + ggtitle("Omicron Infections in NMewfoundland & Labrador, Canada")
  + theme_clean()
)
```

## As at 15th December 2021, NL had 34 active cases of COVID-19 and 2,047 people had recovered.
# https://www.gov.nl.ca/releases/2021/health/1215n04/


```{r message=FALSE, warning=FALSE, fig.width=15, fig.height=10}
source("~/Documents/MUN/SEARCH-ID-MODEL/searchid/macpan2/codes/sir/sir_tmb.R")
sir = spec

## Piecewise Time Variation

beta_changepoints <- c(0, 10, 21, 55, 90)
beta_values <- c(0.40, 0.37, 0.63, 0.70, 0.33)
time_steps = 170
beta = 0.8 
gamma = 0.2 
state_labels = c("S", "I", "R", "cases")

expr = list(
 beta ~ time_var(beta_values, beta_changepoints)
)

# model specification with piece-wise transmission rates
piecewise_spec = (
  sir |> 
    mp_tmb_insert(
      phase="during"
    , at=1L
    , expressions = expr
    , default = list(beta_values = log(beta_values))
    , integers = list(beta_changepoints = beta_changepoints))
  )
# transformed model specification
sir_transformed_spec = mp_tmb_insert(
    model = piecewise_spec
  , phase = "before"
  , at = 1L
  , expressions = list(beta_values ~ exp(log_beta_values))
  , default = list(log_beta_values = log(beta_values))
)

# create simulator object
sir_transformed_spec_simulator = (sir_transformed_spec |> 
                                mp_rk4() |> 
                                mp_simulator(time_steps = 170, outputs = c(state_labels))
                              )
(sir_transformed_spec_simulator
  |> mp_trajectory()
  |> mutate(state = factor(matrix, state_labels))
  |>  ggplot()
 + geom_line(aes(time, value, colour = state))
  + geom_point(aes(time, value, colour = state), size = 0.5)
  + geom_vline(
    aes(xintercept = x),
    linetype = "dashed",
    alpha = 0.5,
    data = data.frame(x = beta_changepoints)
  )+
  labs(x = "Date (Dec 2021  - June 2022)", y = "Omicron Incidence", title = "SEARCH-ID Model Incidence Trajectory With macpan2", color = "") +

 facet_wrap(~ state, scales = "free")
 + theme_clean()
)
```

## Set up the Optimizer

Now we can create an object that can be calibrated.

```{r warning=FALSE, message=FALSE}
sir_calibrator = mp_tmb_calibrator(
    spec = sir_transformed_spec |> mp_rk4() 
  , data = observed_data
  , traj = "cases"  
  
  , par = c("log_beta_values","I", "R")
  , default = list(gamma = gamma, beta = beta)
)

mp_optimize(sir_calibrator)

```

```{r}
euler_coef <- (mp_tmb_coef(sir_calibrator, conf.int=TRUE)
       |> backtrans()
)

euler_coef
```

```{r message=FALSE, warning=FALSE, fig.height = 7, fig.width=10}
plot_fit = function(cal_object) {
  fitted_data = mp_trajectory_sd(cal_object, conf.int=TRUE)
  fitted_data$dates <- seq.Date(from = as.Date("2021-12-01"), by = "day", length.out = nrow(fitted_data))
  fitted_data <- fitted_data[fitted_data$dates > "2021-12-14",]
  observed_data <- observed_data[observed_data$dates > "2021-12-14",]
  ggplot(observed_data, aes(x = dates, y = value, colour = "black"), na.rm = TRUE) +
    geom_line(size = 2) +
    geom_line(aes(x = dates, y = value,colour = "red"), data = fitted_data,  size = 1) +
    geom_ribbon(aes(x = dates, ymin = conf.low, ymax = conf.high), data = fitted_data, alpha = 0.2) +
    labs(x = "Date (Dec 2021  - June 2022)", y = "Omicron True Infections", title = "SEARCH-ID Model Fit With macpan2", color = "") +
    scale_color_manual(labels = c("true incidence", "macpan2 fit"),values = c("black","red")) +
    annotate("text", x = as.Date("2021-12-18"), y = 700, label = expression(beta[2] == 0.20),size = 6,angle = 90, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2021-12-28"), y = 700, label = expression(beta[3] == 5.21),size = 6,angle = 90, hjust = 1,color = "black")+
  annotate("text", x = as.Date("2022-01-30"), y = 550, label = expression(beta[4] == 0.62),size = 6,angle = 0, hjust = 1, color = "black")+
  # annotate("text", x = as.Date("2022-02-05"), y = 3, label = "Alert Level 3",size = 5,angle = 10, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-03-03"), y = 550, label = expression(beta[3] == 0.70),size = 6,angle = 0, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-05-01"), y = 1500, label = expression(beta[0] == 0.82),size = 6, hjust = 1, color = "black")+
    theme_clean() +
    geom_vline(xintercept = as.Date("2022-03-18"), colour = "purple", linetype = 6, size = 1)  +
      # geom_vline(xintercept = as.Date("2022-04-10"), colour = "purple", linetype = 6, size = 2)  +
    geom_vline(xintercept = as.Date("2021-12-23"), colour = "gold4", linetype = 2, size = 1)  +
    geom_vline(xintercept = as.Date("2022-01-03"), colour = "gold4", linetype = 2, size = 1)  +
    geom_vline(xintercept = as.Date("2022-02-06"), colour = "gold4", linetype = 2, size = 1)  +
    geom_vline(xintercept = as.Date("2022-03-14"), colour = "gold4", linetype = 1, size = 1)  +
    annotate("text", x = as.Date("2022-03-05"), y = 2200, label = "Pre-Cancellation of Public \nHealth Emergency Declaration",size=5, hjust=1, color = "darkblue")+
    annotate("text", x = as.Date("2022-05-14"), y = 2200, label = "Post Cancellation of Public \nHealth Emergency Declaration",size=5, hjust=1,color = "darkblue")+
    theme(axis.text.x = element_text(size = 20, angle = 45, hjust = 1),
          axis.title.x = element_text(size = 20, color = "black", face = "bold"),
          axis.text.y = element_text(size = 20),
          axis.title.y = element_text(size = 20, color = "black", face = "bold"),
          plot.title = element_text(size = 18, face = "bold", color = "black", hjust = 0.5),
          legend.position = c(0.75, 0.35),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 15),
          legend.background = element_rect(color = NA),
          legend.margin = margin(0, 0, 0, 0),
          plot.background = element_blank()) +
          theme(plot.title = element_text(hjust = 0.5))
}

# Assuming searchid_calibrator is the calibration object
plot_fit(sir_calibrator)

```

```{r}
spec = mp_tmb_library("starter_models", "sir", package = "macpan2")
sim = mp_simulator(spec, 50, "infection")
data = mp_trajectory(sim)
cal = mp_tmb_calibrator(
    spec,
    data,
    traj = "infection",
    par = "beta",
    default = list(beta = 0.25)
)
mp_optimize(cal)
mp_tmb_coef(cal)  ## requires broom.mixed package

```



