---
title: "R Notebook"
output: html_notebook
---


```{r warning=FALSE, message=FALSE}
set.seed(132628335)
suppressPackageStartupMessages({
pacman::p_load(tidyverse, reshape2, ggplot2, coda, gtools, gridExtra,
                foreach, doParallel, doRNG, tidyr,plyr, pomp, doMC, zoo, 
                devtools, readxl, viridis, tibbletime, tidyquant, lubridate,
                grid, ggthemes, ggh4x, ggsci, ggnewscale, repr, magrittr, 
               coda, xtable, gghighcontrast, superdiag,ggpubr,cowplot)})

base_colors <- scales::hue_pal()(18)
dark_colors <- colorspace::darken(base_colors, 0.3)
lite_colors <- colorspace::lighten(base_colors, 0.3)

library(doParallel)
registerDoParallel(cores = detectCores())
options(scipen = 100, digits = 4)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(pomp)
library(foreach)
library(doFuture)
library(parallel)
library(doParallel)
library(doRNG)
library(coda)
library(ggthemes)
library(coda)
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggthemes)
library(cowplot)
library(minpack.lm)
library(coda)
library(xtable)
library(lubridate) # Elegant date handling
library(incidence) # Package for handling and plotting incidence data
library(EpiEstim)  # Package for calculating pandemic metrics

colors = c("#000000","#31E1F7","#F99417","#E11299","#002B5B","#379237","#D2001A","#6F38C5","#8D7B68","#BFDB38","#820000","#367E18","#2192FF","#C58940",
           "black","orange","yellow","magenta","maroon")
options(scipen = 100, digits = 8)
```

```{r warning=FALSE, message=FALSE}
vacc <- read.csv("~/Documents/MUN/SEARCH-ID-MODEL/searchid/macpan2/data/vaccination-coverage-map.csv")
vacc <- vacc[vacc$prename == "Newfoundland and Labrador",]
vacc$week_end <- as.Date(vacc$week_end, format = "%Y-%m-%d")
vacc <- vacc[c("week_end", "numtotal_atleast1dose","numtotal_fully","numtotal_additional")]

# Calculate weekly vaccination rate
vacc$weekly_2doses <- c(vacc$numtotal_fully[1], diff(vacc$numtotal_fully))
vacc$weekly_booster <- c(vacc$numtotal_additional[1], diff(vacc$numtotal_additional))
vacc <- vacc[(vacc$week_end > "2021-12-01") & (vacc$week_end <= "2022-06-05"),]
rownames(vacc) <- NULL
sum(vacc$weekly_2doses) / 145695
sum(vacc$weekly_booster, na.rm = TRUE) / 286414
```

```{r warning=FALSE, message=FALSE}
# Sample data creation (replace this with actual data loading)
covid_data <- data.frame(
  Date = seq(as.Date("2020-02-23"), as.Date("2021-02-01"), by="month"),
  Africa = runif(12, min = 0, max = 10),
  Oceania = runif(12, min = 0, max = 5),
  South_America = runif(12, min = 10, max = 20),
  North_America = runif(12, min = 20, max = 40),
  Europe = runif(12, min = 30, max = 60),
  Asia_excl_China = runif(12, min = 40, max = 80),
  China = runif(12, min = 5, max = 10)
)

# Ensure data is in the correct format
covid_data$Date <- as.Date(covid_data$Date)

# Melt the data frame for ggplot2
covid_melt <- reshape2::melt(covid_data, id.vars = "Date", variable.name = "Region", value.name = "Cases")

# Generate the plot
ggplot(covid_melt, aes(x = Date, y = Cases, fill = Region)) +
  geom_area() +
  scale_fill_manual(values = c("Africa" = "orange", "Oceania" = "purple", "South_America" = "green",
                               "North_America" = "blue", "Europe" = "darkblue", 
                               "Asia_excl_China" = "red", "China" = "darkred")) +
  labs(title = "Cumulative confirmed COVID-19 cases",
       subtitle = "Confirmed cases is lower than the number of actual cases. The main reason for this is limited testing.",
       x = NULL,
       y = "Number of cases",
       fill = "Region") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
```

```{r warning=FALSE, message=FALSE}
# load data
# serop_data <- read_csv("~/Documents/nl_ba1_two_peak_pmcmc_model/data/case_estimated_infections.csv")
serop_data <- read_csv("~/Documents/MUN/SEARCH-ID-MODEL/searchid/macpan2/data/omicron_estimated_serop.csv",show_col_types = FALSE)
serop_data <- serop_data[serop_data$date > "2021-12-14",]
serop_data$day <- 1 :nrow(serop_data)

searchid_process_step <- Csnippet("
   
    double Beta;

    double N = (S1_0 + E1_0 + A1_0 + I1_0 + R1_0 + H1_0 + C1_0 + D1_0) +
                (V2_0 + E2_0 + A2_0 + I2_0 + R2_0 + H2_0 + C2_0 + D2_0) +
                (V3_0 + E3_0 + A3_0 + I3_0 + R3_0 + H3_0 + C3_0 + D3_0);
    
    //double N1 = 78441;
    //double N2 = 145695;
    //double N3 = 286414;
                 
    double rate[33];
    double dN[33];
    
    S = S1 + V2 + V3;  // all susceptibles
    E = E1 + E2 + E3;  // all exposed
    A = A1 + A2 + A3;  // all asymptomatic
    I = I1 + I2 + I3;  // all infectives
    R = R1 + R2 + R3;  // all recovered
    H = H1 + H2 + H3;  // all hospitalized
    C = C1 + C2 + C3;  // all hospitalized in ICU
    D = D1 + D2 + D3;  // all fatalities encountered
  
    // ##########################################################################
    // define changepoints for transmission due to changes in alert levels
    // ##########################################################################
  
    if(t < 10){
      Beta = Beta_2;
    }
    else if(t >= 10 || t <= 21){
      Beta = Beta_3;
    }
    else if(t > 21 && t <= 55){
      Beta = Beta_4;
    }
    else if(t > 55 & t < 90){
      Beta = Beta_3;
    }
    else{
      Beta = Beta_0;
    }
  
    // #####################################
        // Compute the transition rates
    // #####################################
  
    //-----------------------------------------------------------
    // Transitions for 1-dose vaccinated / unvaccinated
    //-----------------------------------------------------------
  
    rate[1] = (kappa1 * Beta * ((tau * I + zeta * A) / N));  //infection, movement from S1 to E1
    rate[2] = v2;  // rate of second dose uptake to move from S1 to V2
  
    rate[3] = sigma * mu;  //from E1 to A1
    rate[4] = sigma * (1 - mu);  //from E1 to I1
  
    rate[5] = gamma_a;  // from A1 to R1
  
    rate[6] = phi1 * xi1;  //from I1 to H1
    rate[7] = phi1 * (1 - xi1);  //from I1 to R1
  
    rate[8] = omega1 * theta1;  //from H1 to C1
    rate[9] = omega1 * (1 - theta1);  //from H1 to R1
  
    rate[10] = eta1 * lambda1;  //from C1 to D1
    rate[11] = eta1 * (1 - lambda1);  //from C1 to R1
  
    //-----------------------------------------------------------
    // Transitions for 2-dose vaccinated
    //-----------------------------------------------------------
  
    rate[12] = kappa2 * (Beta * ((tau * I + zeta * A) / N));  //infection, movement from V2 to E2
    rate[13] = v3;  // rate of third or booster dose uptake to move from V2 to V3
  
    rate[14] = sigma * mu;  //from E2 to A2
    rate[15] = sigma * (1 - mu);  //from E2 to I2
  
    rate[16] = gamma_a;  // from A2 to R2
  
    rate[17] = phi2 * xi2;  //from I2 to H2
    rate[18] = phi2 * (1 - xi2);  //from I2 to R2
  
    rate[19] = omega2 * theta2;  //from H2 to C2
    rate[20] = omega2 * (1 - theta2);  //from H2 to R2
  
    rate[21] = eta2 * lambda2;  //from C2 to D2
    rate[22] = eta2 * (1 - lambda2);  //from C2 to R2
  
    //-----------------------------------------------------------
    // Transitions for 3-dose/ booster dose vaccinated
    //-----------------------------------------------------------
  
    rate[23] = kappa3 * (Beta * ((tau * I + zeta * A) / N));  //infection, movement from V2 to E2
  
    rate[24] = sigma * mu;  //from E3 to A3
    rate[25] = sigma * (1 - mu);  // from E3 to I3
  
    rate[26] = gamma_a;  // from A3 to R3
  
    rate[27] = phi3 * xi3;  //from I3 to H3
    rate[28] = phi3 * (1 - xi3);  //from I3 to R3
  
    rate[29] = omega3 * theta3;  //from H3 to C3
    rate[30] = omega3 * (1 - theta3);  //from H3 to R3
  
    rate[31] = eta3 * lambda3;  //from C3 to D3
    rate[32] = eta3 * (1 - lambda3);  //from C3 to R3
  
    // #####################################
        // Compute the state transitions
    // #####################################
  
    dN[2] = rpois(rate[2] * dt); // double dose uptake is assumed to be Poisson distributed
    dN[13] = rpois(rate[13] * dt); // booster dose uptake is assumed to be Poisson distributed
  
    reulermultinom(2, S1, &rate[1], dt, &dN[1]);
    reulermultinom(2, E1, &rate[3], dt, &dN[3]);
    reulermultinom(1, A1, &rate[5], dt, &dN[5]);
    reulermultinom(2, I1, &rate[6], dt, &dN[6]);
    reulermultinom(2, H1, &rate[8], dt, &dN[8]);
    reulermultinom(2, C1, &rate[10], dt, &dN[10]);
  
    reulermultinom(2, V2, &rate[12], dt, &dN[12]);
    reulermultinom(2, E2, &rate[14], dt, &dN[14]);
    reulermultinom(1, A2, &rate[16], dt, &dN[16]);
    reulermultinom(2, I2, &rate[17], dt, &dN[17]);
    reulermultinom(2, H2, &rate[19], dt, &dN[19]);
    reulermultinom(2, C2, &rate[21], dt, &dN[21]);
  
    reulermultinom(2, V3, &rate[23], dt, &dN[23]);
    reulermultinom(2, E3, &rate[24], dt, &dN[24]);
    reulermultinom(1, A3, &rate[26], dt, &dN[26]);
    reulermultinom(2, I3, &rate[27], dt, &dN[27]);
    reulermultinom(2, H3, &rate[29], dt, &dN[29]);
    reulermultinom(2, C3, &rate[31], dt, &dN[31]);
  
    // #################################################################
          // Apply transitions to state variables (balance equations)
    // #################################################################
  
    S1 += -dN[1] - dN[2];
    E1 += dN[1] - dN[3] - dN[4];
    A1 += dN[3] - dN[5];
    I1 += dN[4] - dN[6] - dN[7];
    H1 += dN[6] - dN[8] - dN[9];
    C1 += dN[8] - dN[10] - dN[11];
    R1 += dN[5] + dN[7] + dN[9] + dN[11];
    D1 += dN[10];
    Recov1 = dN[5] + dN[7] + dN[9] + dN[11];
  
    V2 += -dN[12] - dN[13] + dN[2];
    E2 += dN[12] - dN[14] - dN[15];
    A2 += dN[14] - dN[16];
    I2 += dN[15] - dN[17] - dN[18];
    H2 += dN[17] - dN[19] - dN[20];
    C2 += dN[19] - dN[21] - dN[22];
    R2 += dN[16] + dN[18] + dN[20] + dN[22];
    D2 += dN[21];
    Recov2 = dN[16] + dN[18] + dN[20] + dN[22];
  
    V3 += dN[13] - dN[23];
    E3 += dN[23] - dN[24] - dN[25];
    A3 += dN[24] - dN[26];
    I3 += dN[25] - dN[27] - dN[28];
    H3 += dN[27] - dN[29] - dN[30];
    C3 += dN[29] - dN[31] - dN[32];
    R3 += dN[26] + dN[28] + dN[30] + dN[32];
    D3 += dN[31];
    Recov3 = dN[26] + dN[28] + dN[30] + dN[32];
  
    S = nearbyint(S1 + V2 + V3);  // all susceptibles
    E = nearbyint(E1 + E2 + E3);  // all exposed
    A = nearbyint(A1 + A2 + A3);  // all asymptomatic
    I = nearbyint(I1 + I2 + I3);  // all infectives
    R = nearbyint(R1 + R2 + R3) / N;  // all recovered
    H = nearbyint(H1 + H2 + H3);  // all hospitalized
    C = nearbyint(C1 + C2 + C3);  // all hospitalized in ICU
    D = nearbyint(D1 + D2 + D3);  // all fatalities encountered
    Recov = nearbyint(Recov1 + Recov2 + Recov3);
    ;
    ")
  
    ############## INITIAL CONDITION SPECIFICATION ############## 
  
searchid_init <- Csnippet("
  
  S1 = nearbyint(S1_0);
  E1 = nearbyint(E1_0);
  A1 = nearbyint(A1_0);
  I1 = nearbyint(I1_0);
  R1 = nearbyint(R1_0);
  H1 = nearbyint(H1_0);
  C1 = nearbyint(C1_0);
  D1 = nearbyint(D1_0);

  V2 = nearbyint(V2_0);
  E2 = nearbyint(E2_0);
  A2 = nearbyint(A2_0);
  I2 = nearbyint(I2_0);
  R2 = nearbyint(R2_0);
  H2 = nearbyint(H2_0);
  C2 = nearbyint(C2_0);
  D2 = nearbyint(D2_0);

  V3 = nearbyint(V3_0);
  E3 = nearbyint(E3_0);
  A3 = nearbyint(A3_0);
  I3 = nearbyint(I3_0);
  R3 = nearbyint(R3_0);
  H3 = nearbyint(H3_0);
  C3 = nearbyint(C3_0);
  D3 = nearbyint(D3_0);

  S = S1 + V2 + V3;  // all susceptibles
  E = E1 + E2 + E3;  // all exposed
  A = A1 + A2 + A3;  // all asymptomatic
  I = I1 + I2 + I3;  // all infectives
  R = R1 + R2 + R3;  // all recovered
  H = H1 + H2 + H3;  // all hospitalized
  C = C1 + C2 + C3;  // all hospitalized in ICU
  D = D1 + D2 + D3;  // all fatalities encountered

  Recov1 = 4090;
  Recov2 = 4090;
  Recov3 = 4090;
  Recov =  Recov1 + Recov2 + Recov3;
  ")

############## DEFINE PROCESS MODEL ############## 
  # Defines the likelihood function
  
  # dmeas <- Csnippet("
  #   if (Beta_0 < 0 || Beta_2 < 0 || Beta_3 < 0 || Beta_4 < 0 || gamma_a < 0 || death_rate < 0 || hosp_rate < 0 || disp < 0) {
  #     lik = (give_log) ? R_NegInf : 0.0;
  #   } else {
  #     // lik = dnbinom_mu(est_inci_serop, k,  Recov, give_log) + dnbinom_mu(death, 1, D * death_rate, give_log) + dpois(hosp, H * //hosp_rate , give_log);
  #       lik = dpois(nearbyint(est_inci_serop), disp * Recov, give_log) + dnbinom_mu(nearbyint(death), 1, D * death_rate, give_log) + dpois(nearbyint(hosp), H * hosp_rate , give_log);
  #     if (!give_log && lik <= 0) {
  #       lik = R_NegInf;
  #     } else if (!give_log) {
  #       lik = log(lik);
  #     }
  #   }
  # ")

dmeas <- Csnippet("
    if (Beta_0 < 0 || Beta_2 < 0 || Beta_3 < 0 || Beta_4 < 0 || gamma_a < 0 || death_rate < 0 || hosp_rate < 0 || disp < 0) {
      lik = (give_log) ? R_NegInf : 0.0;
    } else {
      lik = dpois(nearbyint(est_inci_serop), disp * Recov, give_log) + dpois(nearbyint(death), D * death_rate, give_log) + dpois(nearbyint(hosp), H * hosp_rate , give_log);
      lik = (give_log) ? lik : exp(lik);
    }
  ")

  ############## DEFINE PROCESS SIMULATOR ##############
  # Generates observations based on the specified distribution

  rmeas <- Csnippet("
    if (Beta_0 < 0 || Beta_2 < 0 || Beta_3 < 0 || Beta_4 < 0 || gamma_a < 0 || death_rate < 0 || hosp_rate < 0 || disp < 0) {
      Rf_error(\"Invalid state values\");
      }
    else{
      //est_inci_serop = rnbinom_mu(k, Recov);
      est_inci_serop = rpois(disp * Recov);
      hosp = rpois(H * hosp_rate);
      death = rpois(D * death_rate);
      }
    ")

  ############## DEFINE MODEL PARAMETER ############## 
  
  state_var <- c(
    "S", "E", "A", "I", "R","H", "C", "D",
    "S1", "E1", "A1", "I1", "R1","H1", "C1", "D1",
    "V2", "E2", "A2", "I2", "R2","H2", "C2", "D2",
    "V3", "E3", "A3", "I3", "R3","H3", "C3", "D3",
    "Recov1","Recov2","Recov3","Recov")
  
fixed_params_names <- c(
  "kappa1", "kappa2", "kappa3","phi1","phi2","phi3", 
  "eta1","eta2","eta3","v2","v3","tau", "zeta", 
  "lambda1", "lambda2","lambda3","theta1","theta2","theta3", 
  "omega1", "omega2","omega3","xi1","xi2","xi3", "mu", "sigma",
  "S1_0", "E1_0", "A1_0", "I1_0", "R1_0", "H1_0", "C1_0", "D1_0",
  "V2_0", "E2_0", "A2_0", "I2_0", "R2_0", "H2_0", "C2_0", "D2_0",
  "V3_0", "E3_0", "A3_0", "I3_0", "R3_0", "H3_0", "C3_0", "D3_0") 

parameters_to_estimate <- c("Beta_0","Beta_2","Beta_3","Beta_4","gamma_a","death_rate", "hosp_rate", "disp") 

paramnames <- c(parameters_to_estimate, fixed_params_names)
  
  ############## INITIAL PARAMETERS ############## 
# Beta_0 = 0.6620067, Beta_2 = 0.4400276, Beta_3 = 0.7550420, Beta_4 = 0.660000,	
# Beta_0 = 0.59507704, Beta_2 = 0.58752579, Beta_3 = 0.7250368, Beta_4 = 0.695509096,
# 0.6270039	0.5964456	0.7232555	0.7009087	0.9709016				
# Beta_0 = 0.300039, Beta_2 = 0.715456, Beta_3 = 0.7300555, Beta_4 = 0.5456,
# 0.44060969	0.81269933	0.72880427	0.50398741	0.79915688	0.0036563906	0.7394517	
#Beta_0 = 0.100039, Beta_2 = 0.715456, Beta_3 = 0.7300555, Beta_4 = 0.5456,gamma_a = 1/14
												
initial_params = c(Beta_0 = 0.15458531, Beta_2 = 0.74118148, Beta_3 = 0.72077776, Beta_4 = 0.54050699,
                 gamma_a = 0.069757085, sigma = 0.35, death_rate = 0.79812553, hosp_rate = 0.0059967661,
                 mu = 0.6,  xi1 = 0.15, xi2 = 0.15, xi3 = 0.15, disp = 0.73652562,
                 kappa1 = 1, kappa2 = 0.91, kappa3 = 0.3, eta1 = 1/5.5, eta2 = 1/5.5, eta3 = 1/5.5,
                 phi1 = 1/5, phi2 = 1/5, phi3 = 1/5, theta1 = 0.007, theta2 = 0.005, theta3 = 0.0025,
                 omega1 = 1/7, omega2 =  1/7, omega3 =  1/7, lambda1 = 0.25, lambda2 = 0.156, lambda3 = 0.150,
                 tau = 0.799, zeta = 0.75, v2 = 0.2828, v3 = 0.1359,
                 S1_0 = 73896, E1_0 = 438, A1_0 = 10, I1_0 = 10, R1_0 = 4918, H1_0 = 0, C1_0 = 0, D1_0 = 0,
                 V2_0 = 139266, E2_0 = 438, A2_0 = 10, I2_0 = 10, R2_0 = 4918, H2_0 = 0, C2_0 = 0, D2_0 = 0,
                 V3_0 = 281265, E3_0 = 438, A3_0 = 10, I3_0 = 5, R3_0 = 4918, H3_0 = 0, C3_0 = 0, D3_0 = 0)

serop_data |>
  dplyr::select(day,est_inci_serop, hosp,death) |>
  pomp(
    times = "day",
    t0 = -4,
    rprocess = discrete_time(searchid_process_step, delta.t = 1.0),
    rinit = searchid_init,
    params = initial_params,
    rmeasure = rmeas,
    dmeasure = dmeas,
    accumvars = c("Recov1","Recov2","Recov3","Recov"),
    obsnames = c("est_inci_serop", "hosp","death"),
    paramnames = paramnames,
    statenames = state_var
  ) -> Omicron_PMCMC
```

```{r message=FALSE, warning=FALSE, fig.height = 7, fig.width=10}
Omicron_PMCMC |>
  simulate(params = initial_params,nsim=1, format="data.frame", include.data=TRUE, seed = 2024) |>
    dplyr:::select.data.frame(c(".id","day","est_inci_serop","R")) -> M
M1 <- M[(M$.id == "data"),]
M2 <- M[(M$.id != "data"),]

M1$date <- dates <- seq.Date(from = as.Date("2021-12-15"), by = "day", length.out = nrow(M1))
M2$date <- dates <- seq.Date(from = as.Date("2021-12-15"), by = "day", length.out = nrow(M2))
M <- rbind(M1,M2)
M <- M[M$date > "2021-12-14",]
rownames(M) <- NULL

M |> 
  ggplot(aes(x = date, y = est_inci_serop, color = ifelse(.id=="data","data","simulation"), group = .id)) +
  geom_point(size = 1) +
  geom_smooth(method = 'loess', span = 0.15, linetype = 6, se = FALSE, size = 1) +
  scale_color_manual(labels = c("True Incidence", "Model Sim."),values = c("black","red")) +
  labs(x = "Date", y = "Omicron Cases", title = "SEARCH-ID Model Fit Using Calibrated Parameters", color = "") +
  annotate("text", x = as.Date("2021-12-18"), y = 1200, label = "Alert Level 2",size = 6,angle = 90, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2021-12-28"), y = 1200, label = "Alert Level 3",size = 6,angle = 90, hjust = 1,color = "black")+
  annotate("text", x = as.Date("2022-02-02"), y = 1200, label = "Alert Level 4",size = 6,angle = 0, hjust = 1, color = "black")+
  # annotate("text", x = as.Date("2022-02-05"), y = 3, label = "Alert Level 3",size = 5,angle = 10, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-03-04"), y = 1200, label = "Alert Level 3",size = 6,angle = 0, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-04-29"), y = 1200, label = "",size = 6, hjust = 1, color = "black")+
  theme_clean() +
  geom_vline(xintercept = as.Date("2022-03-18"), colour = "purple", linetype = 6, size = 1)  +
    # geom_vline(xintercept = as.Date("2022-04-10"), colour = "purple", linetype = 6, size = 2)  +
  geom_vline(xintercept = as.Date("2021-12-23"), colour = "black", linetype = 2, size = 1)  +
  geom_vline(xintercept = as.Date("2022-01-03"), colour = "black", linetype = 2, size = 1)  +
  geom_vline(xintercept = as.Date("2022-02-06"), colour = "black", linetype = 2, size = 1)  +
  geom_vline(xintercept = as.Date("2022-03-14"), colour = "black", linetype = 2, size = 1)  +
  annotate("text", x = as.Date("2022-03-05"), y = 2200, label = "Pre-Cancellation of Public \nHealth Emergency Declaration",size=5, hjust=1, color = "darkblue")+
  annotate("text", x = as.Date("2022-05-14"), y = 2200, label = "Post Cancellation of Public \nHealth Emergency Declaration",size=5, hjust=1,color = "darkblue")+
  theme(axis.text.x = element_text(size = 20, angle = 45, hjust = 1),
        axis.title.x = element_text(size = 20, color = "black", face = "bold"),
        axis.text.y = element_text(size = 20),
        axis.title.y = element_text(size = 20, color = "black", face = "bold"),
        plot.title = element_text(size = 18, face = "bold", color = "black", hjust = 0.5),
        legend.position = c(0.75, 0.35),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.background = element_rect(color = NA),
        legend.margin = margin(0, 0, 0, 0),
        plot.background = element_blank()) +
        theme(plot.title = element_text(hjust = 0.5))
```

```{r warning=FALSE, message=FALSE}
Omicron_PMCMC |>
  simulate(params = initial_params, nsim = 1,as.data.frame = TRUE, include.data = TRUE, seed = 2024) |>
  data.frame()|>
  dplyr::select(c("day","est_inci_serop","S","E","A","I","R","H","C","D", "Recov")) -> tg

tg$Rpercap <- tg$R #/ total_population
dates <- seq.Date(from = as.Date("2021-12-15"), by = "day", length.out = nrow(tg))
tg$dates <- dates

tg <- tg[(tg$dates > "2021-12-14") & (tg$dates < "2022-06-03"),]
serop_data <- serop_data[serop_data$date > "2021-12-14",]
rownames(tg) <- NULL

ggplot() +
  geom_point(data = tg, aes(x = dates, y = R, color = "Recovery Per Capita"), size = 1) +
  geom_point(data = serop_data, aes(x = date, y = daily_serop, color = "CITF Seroprevalence"), size = 1) +
  scale_color_manual(name = NULL,values = c("Recovery Per Capita" = "darkgreen","CITF Seroprevalence" = "brown")) +
  labs(x = "Date", y = "Seroprevalence", title = "Recovery Per Capita and CITF Seroprevalence", color = "") +
  theme_clean() +
  theme(axis.text.x = element_text(size = 20, angle = 45, hjust = 1),
        axis.title.x = element_text(size = 20, color = "black", face = "bold"),
        axis.text.y = element_text(size = 20),
        axis.title.y = element_text(size = 20, color = "black", face = "bold"),
        plot.title = element_text(size = 20, face = "bold", color = "black", hjust = 0.5),
        legend.position = c(0.25, 0.75),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20),
        legend.background = element_rect(color = NA),
        legend.margin = margin(0, 0, 0, 0),
        plot.background = element_blank()) +
        theme(plot.title = element_text(hjust = 0.5))
```

```{r warning=FALSE, message=FALSE}
plan(multicore)
cl = makeCluster(1L)
registerDoParallel(cores = detectCores())
registerDoRNG(625904618)

foreach(i=1:10, .combine = c) %dopar% {
  library(pomp)
  Omicron_PMCMC |> pfilter(params= initial_params,  Np = 5000)
} -> pf

plot(pf)
pf %>% logLik() %>% logmeanexp(se = TRUE, ess=TRUE)
```

```{r warning=FALSE, message=FALSE}
############## parallelize on clusters ############## 
set.seed(2024)
num_clusters <- parallel::makeCluster(parallel::detectCores())
registerDoParallel(num_clusters)
registerDoRNG(1000242057)
library(pomp)
############## Run and calibrate model using PMCMC ##############

num_chains <- 4
num_mcmc <- 2000
num_np <- 5000

start_time = Sys.time()
paste0("Model Training started at: ",start_time)
bake(file = "~/Documents/MUN/SEARCH-ID-MODEL/searchid/pomp/data/pmcmc_bakei.rds", {
  foreach(i = 1:num_chains, .combine = c, .packages = c("pomp","tidyverse")) %dopar%{
    Omicron_PMCMC |>
      pmcmc(
        params = initial_params,
        Nmcmc = num_mcmc,
        Np = num_np,
        dprior = function (Beta_0, Beta_2, Beta_3, Beta_4, gamma_a, death_rate, hosp_rate, ..., log = TRUE) {
            params = c(Beta_0, Beta_2, Beta_3, Beta_4, gamma_a, death_rate, hosp_rate)
            means = c(0.15, 0.74, 0.720, 0.54, 0.069, 0.798, 0.0059)
            sds = c(0.1, 0.15, 0.15, 0.15, 0.04, 0.1, 0.005)
            # Calculate the log-prior
            lp <- sum(dnorm(params, mean = means, sd = sds, log = TRUE))
            # Print out the current log-likelihood
            print(paste("Log-likelihood:", lp))
            
            if (log) return(lp) else return(exp(lp))},
        proposal = mvn_diag_rw(c(Beta_0 = 0.01, Beta_2 = 0.01, Beta_3 = 0.01, Beta_4 = 0.01, 
                                 gamma_a = 0.001,death_rate = 0.001, hosp_rate = 0.001, disp = 0.001)),
        paramnames = c("Beta_0","Beta_2","Beta_3","Beta_4","gamma_a","death_rate","hosp_rate","disp"))
    } -> pmcmc_chains  
  attr(pmcmc_chains,"ncpu") <- getDoParWorkers()
  pmcmc_chains
}, seed = 0, kind = "L'Ecuyer") -> pmcmc_chains

saveRDS(pmcmc_chains, "~/Documents/MUN/SEARCH-ID-MODEL/searchid/pomp/data/chains_pmcmci.rds")
  
# likelihood estimate for search results
bake(file = "~/Documents/MUN/SEARCH-ID-MODEL/searchid/pomp/data/eval_pmcmci.rds", {
  foreach(pmcmc_run = pmcmc_chains, .combine = rbind) %dopar% {
    ll = replicate(10, logLik(pfilter(pmcmc_run, Np = 20000))) |>
      logmeanexp(se = TRUE)
    coef(pmcmc_run) |> bind_rows() |> bind_cols(loglik = ll[1], loglik.se = ll[2])
  } -> pmcmc_results
  attr(pmcmc_results,"ncpu") <- getDoParWorkers()
  pmcmc_results
}, seed = 0, kind = "L'Ecuyer") -> pmcmc_results

stopCluster(num_clusters)

end_time = Sys.time()
paste0("SEARCH-ID Model took ", round(difftime(end_time, start_time, units="hours"),3),"hrs", " - " , round(difftime(end_time, start_time, units="min"),3), "mins", " - ", round(difftime(end_time, start_time, units="secs"),3),"sec", " to run and calibrate parameters.")
write.csv(pmcmc_results,"~/Documents/MUN/SEARCH-ID-MODEL/searchid/pomp/data/calib_params_pmcmci.csv",row.names = FALSE)
```

```{r warning=FALSE, message=FALSE}
############## Save model and parameters and print results ############## 
t(sapply(pmcmc_chains, coef)) |> 
  as_tibble() |>
  dplyr::bind_cols(tibble(logLik = pmcmc_results[,1],logLik_se = pmcmc_results[,2])) -> pmcmc_params_df

pmcmc_params_opt <- pmcmc_params_df[pmcmc_params_df["logLik"] == max(pmcmc_params_df["logLik"]),]
pmcmc_params_opt <- pmcmc_params_opt[paramnames]
pmcmc_params_opt
```

```{r warning=FALSE, message=FALSE, fig.height = 7, fig.width = 7}
pmcmc_chains |>
  traces(c(parameters_to_estimate,"loglik")) -> pmcmc_chains_est 
  
plot(pmcmc_chains_est)
```

```{r warning=FALSE, message=FALSE, fig.height = 7, fig.width = 7}
pmcmc_chains |>
  traces(c(parameters_to_estimate,"loglik")) -> pmcmc_chains_est 

gelman_diag_result <- gelman.diag(pmcmc_chains_est, confidence = 0.95, transform = FALSE, multivariate = TRUE)
print(gelman_diag_result)

gelman.plot(pmcmc_chains_est, autoburnin = TRUE)
```

```{r warning=FALSE, message=FALSE, fig.width=12, fig.height=7}
Omicron_PMCMC |>
  simulate(params = pmcmc_params_opt, nsim=1, format="data.frame", include.data=TRUE, seed = 2024) |>
    dplyr:::select.data.frame(c(".id","day","est_inci_serop", "hosp","death","R")) -> yt

yt1 <- yt[(yt$.id == "data"),]
yt2 <- yt[(yt$.id != "data"),]
yt1$date <- dates <- seq.Date(from = as.Date("2021-12-15"), by = "day", length.out = nrow(yt1))
yt2$date <- dates <- seq.Date(from = as.Date("2021-12-15"), by = "day", length.out = nrow(yt2))
yt <- rbind(yt1,yt2)
yt <- yt[yt$date > "2021-12-14",]
rownames(yt) <- NULL

J <- ggplot(data = yt, aes(x = date, y = est_inci_serop, color = ifelse(.id=="data","data","simulation"), group = .id)) +
  geom_point(size = 5) +
  geom_smooth(span = 0.15, linetype = 6, se = FALSE, size = 5) +
  scale_color_manual(labels = c("Est. New Cases", "SEARCH-ID Sim."),values = c("black","red")) +
  labs(x = "Date", y = "Omicron Cases", title = "SEARCH-ID Model Fit Using Calibrated Parameters", color = "") +
  theme_clean() +
  annotate("text", x = as.Date("2021-12-18"), y = 1000, label = "Alert Level 2",size = 15,angle = 90, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-01-01"), y = 1000, label = "Alert Level 3",size = 15,angle = 90, hjust = 1,color = "black")+
  annotate("text", x = as.Date("2022-02-02"), y = 1000, label = "Alert Level 4",size = 15,angle = 0, hjust = 1, color = "black")+
  # annotate("text", x = as.Date("2022-02-05"), y = 3, label = "Alert Level 3",size = 5,angle = 10, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-03-04"), y = 1500, label = "Alert Level 3",size = 15,angle = 0, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-05-20"), y = 700, label = "",size = 15, hjust = 1, color = "black")+
  theme_clean() +
  geom_vline(xintercept = as.Date("2022-03-18"), colour = "purple", linetype = 6, size = 4) +
  geom_vline(xintercept = as.Date("2021-12-23"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-01-03"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-02-06"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-03-14"), colour = "gold4", linetype = 2, size = 4)  +
  annotate("text", x = as.Date("2022-03-03"), y = 2200, label = "Pre-Cancellation of Public \nHealth Emergency Declaration",size=15, hjust=1, color = "navy")+
  annotate("text", x = as.Date("2022-05-27"), y = 2200, label = "Post Cancellation of Public \nHealth Emergency Declaration",size=15, hjust=1,color = "navy")+
  theme(axis.text.x = element_text(size = 40, angle = 45, hjust = 1),
        axis.title.x = element_text(size = 40, color = "black", face = "bold"),
        axis.text.y = element_text(size = 40),
        axis.title.y = element_text(size = 40, color = "black", face = "bold"),
        plot.title = element_text(size = 40, face = "bold", color = "black", hjust = 0.5),
        legend.position = c(0.75, 0.35),
        legend.title = element_text(size = 40),
        legend.text = element_text(40),
        legend.background = element_rect(color = NA),
        legend.margin = margin(0, 0, 0, 0),
        plot.background = element_blank()) +
        theme(plot.title = element_text(hjust = 0.5))

K <- ggplot() +
  geom_point(data = serop_data[serop_data$date > "2021-12-14",], aes(x = date, y = daily_serop)) +
  geom_point(data = yt, aes(x = date, y = R, color = "SEARCHID Model Recovery Per Capita"), size = 4) +
  geom_point(data = serop_data[serop_data$date > "2021-12-14",], aes(x = date, y = daily_serop, color = "CITF Seroprevalence Estimate"), size = 4) +
  scale_color_manual(name = NULL,values = c("SEARCHID Model Recovery Per Capita" = "navy","CITF Seroprevalence Estimate" = "brown")) +
  geom_smooth(span = 0.15, linetype = 6, se = FALSE) +
  scale_color_manual(labels = c("CITF Seroprevalence Estimatee", "SEARCHID Model Recovery Per Capita"),values = c("navy","brown")) +
  labs(x = "Date", y = "Seroprevalence", title = "CITF Seroprevalence Vrs SEARCHID Model Recovery Per Capita", color = "") +
  theme_clean() +
  theme(axis.text.x = element_text(size = 40, angle = 45, hjust = 1),
        axis.title.x = element_text(size = 40, color = "black", face = "bold"),
        axis.text.y = element_text(size = 40),
        axis.title.y = element_text(size = 40, color = "black", face = "bold"),
        plot.title = element_text(size = 40, face = "bold", color = "black", hjust = 0.5),
        legend.position = c(0.25, 0.75),
        legend.title = element_text(size = 40),
        legend.text = element_text(size = 40),
        legend.background = element_rect(color = NA),
        legend.margin = margin(0, 0, 0, 0),
        plot.background = element_blank()) +
        theme(plot.title = element_text(hjust = 0.5))

S <- ggplot(data = yt, aes(x = date, y = hosp, color = ifelse(.id=="data","data","simulation"), group = .id)) +
  geom_line(size = 3) +
  scale_color_manual(labels = c("Hospitalized", "SEARCH-ID Sim."),values = c("red","darkgreen")) +
  labs(x = "Date", y = "Hospitalized", title = "SEARCH-ID Model Fit Using Calibrated Parameters", color = "") +
  theme_clean() +
  annotate("text", x = as.Date("2021-12-18"), y = 6, label = "Alert Level 2",size = 15,angle = 90, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-01-01"), y = 9, label = "Alert Level 3",size = 15,angle = 90, hjust = 1,color = "black")+
  annotate("text", x = as.Date("2022-02-02"), y = 8, label = "Alert Level 4",size = 15,angle = 0, hjust = 1, color = "black")+
  # annotate("text", x = as.Date("2022-02-05"), y = 3, label = "Alert Level 3",size = 5,angle = 10, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-03-04"), y = 8, label = "Alert Level 3",size = 15,angle = 0, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-05-28"), y = 8, label = "",size = 15, hjust = 1, color = "black")+
  theme_clean() +
  geom_vline(xintercept = as.Date("2022-03-18"), colour = "purple", linetype = 6, size = 4) +
  geom_vline(xintercept = as.Date("2021-12-23"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-01-03"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-02-06"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-03-14"), colour = "gold4", linetype = 2, size = 4)  +
  annotate("text", x = as.Date("2022-03-10"), y = 13, label = "Pre-Cancellation of Public \nHealth Emergency Declaration",size=15, hjust=1, color = "navy")+
  annotate("text", x = as.Date("2022-05-19"), y = 13, label = "Post Cancellation of Public \nHealth Emergency Declaration",size=15, hjust=1,color = "navy")+
  theme(axis.text.x = element_text(size = 40, angle = 45, hjust = 1),
        axis.title.x = element_text(size = 40, color = "black", face = "bold"),
        axis.text.y = element_text(size = 40),
        axis.title.y = element_text(size = 40, color = "black", face = "bold"),
        plot.title = element_text(size = 40, face = "bold", color = "black", hjust = 0.5),
        legend.position = c(0.75, 0.80),
        legend.title = element_text(size = 40),
        legend.text = element_text(size = 40),
        legend.background = element_rect(color = NA),
        legend.margin = margin(0, 0, 0, 0),
        plot.background = element_blank()) +
        theme(plot.title = element_text(hjust = 0.5))

W <- ggplot(data = yt, aes(x = date, y = death, color = ifelse(.id=="data","data","simulation"), group = .id)) +
  geom_line(size = 3) +
  scale_color_manual(labels = c("Death", "SEARCH-ID Sim."),values = c("blue","maroon")) +
  labs(x = "Date", y = "Deaths", title = "SEARCH-ID Model Fit Using Calibrated Parameters", color = "") +
  theme_clean() +
  annotate("text", x = as.Date("2021-12-18"), y = 6, label = "Alert Level 2",size = 15,angle = 90, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-01-01"), y = 9, label = "Alert Level 3",size = 15,angle = 90, hjust = 1,color = "black")+
  annotate("text", x = as.Date("2022-02-02"), y = 8, label = "Alert Level 4",size = 15,angle = 0, hjust = 1, color = "black")+
  # annotate("text", x = as.Date("2022-02-05"), y = 3, label = "Alert Level 3",size = 5,angle = 10, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-03-04"), y = 8, label = "Alert Level 3",size = 15,angle = 0, hjust = 1, color = "black")+
  annotate("text", x = as.Date("2022-05-28"), y = 8, label = "",size = 15, hjust = 1, color = "black")+
  theme_clean() +
  geom_vline(xintercept = as.Date("2022-03-18"), colour = "purple", linetype = 6, size = 4) +
  geom_vline(xintercept = as.Date("2021-12-23"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-01-03"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-02-06"), colour = "gold4", linetype = 2, size = 4)  +
  geom_vline(xintercept = as.Date("2022-03-14"), colour = "gold4", linetype = 2, size = 4)  +
  annotate("text", x = as.Date("2022-03-10"), y = 13, label = "Pre-Cancellation of Public \nHealth Emergency Declaration",size=15, hjust=1, color = "navy")+
  annotate("text", x = as.Date("2022-05-19"), y = 13, label = "Post Cancellation of Public \nHealth Emergency Declaration",size=15, hjust=1,color = "navy")+
  theme(axis.text.x = element_text(size = 40, angle = 45, hjust = 1),
        axis.title.x = element_text(size = 40, color = "black", face = "bold"),
        axis.text.y = element_text(size = 40),
        axis.title.y = element_text(size = 40, color = "black", face = "bold"),
        plot.title = element_text(size = 40, face = "bold", color = "black", hjust = 0.5),
        legend.position = c(0.75, 0.70),
        legend.title = element_text(size = 40),
        legend.text = element_text(size = 40),
        legend.background = element_rect(color = NA),
        legend.margin = margin(0, 0, 0, 0),
        plot.background = element_blank()) +
        theme(plot.title = element_text(hjust = 0.5))
```

```{r warning=FALSE, message=FALSE}
J_K <- plot_grid(J, K, ncol = 2, labels=c("J", "K"),align = "hv", label_size = 45)
S_W <- plot_grid(S, W, ncol = 2, labels=c("S", "W"),align = "hv", label_size = 45)
J_K_S_W <- plot_grid(J_K, S_W, nrow = 2, rel_heights = c(1, 1, 1))
J_K_S_W
```

